name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t kirpich .
      - name: Tests
        run: docker run -ti kirpich /bin/bash -c "make test"