name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodule
        shell: bash
        run: |
          git submodule update --init --recursive
      - name: Build
        run: docker build -t kirpich .
      - name: Tests
        run: COMPOSE_INTERACTIVE_NO_CLI=true docker run --tty kirpich /bin/bash -c "make test"